
import PropTypes from 'prop-types';

export const propTypes = {
    className: PropTypes.string,
    tagName: PropTypes.string,
    row: PropTypes.bool,
    col: PropTypes.bool,
    padded: PropTypes.bool,
    basis: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    auto: PropTypes.bool,
    fluid: PropTypes.bool,
    fixed: PropTypes.bool,
    centered: PropTypes.bool,
    reversed: PropTypes.bool,
    bordered: PropTypes.bool,
    borderLeft: PropTypes.bool,
    borderRight: PropTypes.bool,
    borderTop: PropTypes.bool,
    borderBottom: PropTypes.bool,
    scrollX: PropTypes.bool,
    scrollY: PropTypes.bool,
    wrap: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
    justify: PropTypes.oneOf(['start', 'end', 'center', 'spaceBetween', 'spaceAround', 'spaceEvenly']),
    align: PropTypes.oneOf(['start', 'end', 'center', 'stretch', 'baseline']),
    alignSelf: PropTypes.oneOf(['start', 'end', 'center', 'baseline', 'stretch']),
    alignContent: PropTypes.oneOf(['start', 'end', 'center', 'stretch', 'spaceBetween', 'spaceAround']),
    order: PropTypes.number,
    grow: PropTypes.number,
    shrink: PropTypes.number,
    padding: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    margin: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    width: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    height: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    minWidth: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    minHeight: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    maxWidth: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    maxHeight: PropTypes.oneOfType([PropTypes.number, PropTypes.string])
};

export const defaultProps = {
    className: '',
    tagName: 'div',
    row: true,
    col: false,
    padded: false,
    basis: null,
    auto: false,
    fluid: true,
    fixed: false,
    centered: false,
    reversed: false,
    bordered: false,
    borderLeft: false,
    borderRight: false,
    borderTop: false,
    borderBottom: false,
    scrollX: false,
    scrollY: false,
    wrap: false,
    justify: null,
    align: null,
    alignSelf: null,
    alignContent: null,
    order: null,
    grow: null,
    shrink: null,
    padding: null,
    width: null,
    height: null,
    minWidth: null,
    minHeight: null,
    maxWidth: null,
    maxHeight: null
};
